### ISSUE TITLE
Waterfox Support Please

### ISSUE THREAD

**Issue by esotericDisciple** [sereneblue/chameleon#107]
The webextension code seems to be available in whatever older version of Firefox that Waterfox is using, and since "Classic Theme Restorer" is a must, is there a way to build the addon for Waterfox?

**Comment by sereneblue** [comment]
Unfortunately, Chameleon only supports FF59+. Waterfox is based on FF56, so you can still use Random Agent Spoofer. You _can_ fork Chameleon and lower the minimum supported version, however, in order to use script injection (if you want to spoof your profile), you need a WebExtension API that was introduced in FF59.
