### ISSUE TITLE
[QUE/REQ] How to define only some specific UA's for some sites?

### ISSUE THREAD

**Issue by madhook** [sereneblue/chameleon#129]
…and leave all other settings working for these sites.

Now, as I can see, I can set only one UA for all urls in whitelist. 
For websites from whitelist not all settings are accessible. For example, 'Timezone' not spoofing for website from whitelist. I can't change this.
It was creat if I can just define customized profile (with all settings) for a specific site.  It will be simple and useful.

**Comment by sereneblue** [comment]
I've added timezone spoofing to the whitelist editor.

Unfortunately, I won't be adding profiles to the whitelist editor.

**Comment by WPFilmmaker** [comment]
@sereneblue
I would like to request too the possibility to add a list of website with a customized ua so that everytime you access the website in the list, chameleon knows what to do automatically. Basically a custom user agent but on a per-website-base.

May I ask why you don't want to add this feature? Hope you will reply^^

If such list could create troubles with many websites, maybe you could restrict the number of sites to be added. I am requesting this feature because of the increasing number of websites which "work better/only with Chrome" and are unusable with FF (some don't even let you access them unless you change browser...). 

For example the new version of skype for web doesn't work with FF(it says change your browser)...changing the ua to edge magically makes it work...it is really a pain for FF users :(

**Comment by sereneblue** [comment]
I started working on adding profiles to the whitelist editor but it required more work than I was willing to do (I'm trying to cut back on Chameleon development!). It'll take some time, but I'll add the feature. The existing whitelist profile option will be deprecated for something simpler.

**Comment by WPFilmmaker** [comment]
@sereneblue Thanks! And thanks for all the hard work you put! I hope the project won't be abandoned, it is really essential :)
