### ISSUE TITLE
Thicking "Disable Authorization" prevents to log in  ProtonMail

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#142]
All is in the title. in the title. I don't know whether or not this can be fixed (as the window.name problem has been fixed for disqus).  But the (abandonned?) addon [Block HTTP Authentication](https://addons.mozilla.org/en-US/firefox/addon/block-http-authentication/) doesn't prevent to log in Protonmail (maybe just because it  blocks HTTP authentication requests only  for image, video and audio, though).

v 0.11.4 on FF65 W7 64

**Comment by sereneblue** [comment]
The extension you linked is how I should have implemented this feature. I did some digging into how the HTTP Auth can be used for malicious purposes and I stumbled upon [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1357835). Now I understand why this was probably added to RAS.

This will be fixed in the next update. Thanks again for the helpful issue! Your help is much appreciated. :)
