### ISSUE TITLE
Compatibility With Firefox 55

### ISSUE THREAD

**Issue by koalaverde** [sereneblue/chameleon#155]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Comment by koalaverde** [comment]
I Read in this post https://github.com/sereneblue/chameleon/issues/5 the compatiblity of chameleon on firefox 55, i tried but i can not install chameleon on firefox 55

**Comment by sereneblue** [comment]
Chameleon is compatible with FF59+. That issue was created before Chameleon used the [contentScript](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts) API for script injection.

The minimum version can be found here:
https://github.com/sereneblue/chameleon/blob/master/src/manifest.json
