### ISSUE TITLE
Enhancement : add elements to the whitelist should be simpler

### ISSUE THREAD

**Issue by GLLM** [sereneblue/chameleon#16]
Hi !

since the devs is quite fast to react, I take advantage of it :

adding a URL to the whitelist should be simpler :
* today, the user has to type {["url","actual_url]} ...
* ideally, the user adds the url and select in a drop down list whatever whitelist category he may chose : url, ...
at the moment I believe one can only add urls ... so why not enabling this by having the user input one url per line (myabe with a comma at the end of the lnie, for parsing sake) ?

Thanks !
GLLM

**Comment by sereneblue** [comment]
I haven't put much thought into the whitelist feature yet. This does seem like it'd be a lot more convenient for users. I'll makes changes to the UI once I begin working on the advanced whitelisting features.

**Comment by 945fc41467** [comment]
A little suggestion : rather than thinking “white list“, you should think as “profiles”. Why not add the possibility to create different presets with a name for each and a url list for each (except the first one which should be the “default”) ? If the url match, the switching would be automatic.

It would be really simpler for user as it would have the same interface (the one already existing) for each preset.

**Comment by sereneblue** [comment]
That's a good idea but it adds some complexity to the addon. There are a few structural things I'd need to improve before implementing it.

**Comment by sereneblue** [comment]
Unfortunately, I won't add whitelist profiles. It's a bit more complex than I'm willing to work on.

I have made it simpler to manage your whitelist in v0.8.5 and implemented some of the options from RAS. Check out the [wiki](https://github.com/sereneblue/chameleon/wiki/Whitelist/) for more info.
