### ISSUE TITLE
Timezone spoofing not working on YouTube

### ISSUE THREAD

**Issue by zygoteplanets** [sereneblue/chameleon#166]
While waiting for a live stream to begin, YouTube first displays the time that the stream will begin in CDT then a second later changes to my real timezone time.

## Relevant settings
Different timezone selected and "Enable script injection" is selected.
WebRTC is off

## Context (Environment)
Firefox 64.0.2 Windows 7
Chamelion 0.11.10

**Comment by sereneblue** [comment]
Are you referring to the the time displayed in the container with `Waiting for [Youtuber name]`?

**Comment by zygoteplanets** [comment]
More like what time the stream will start in my region.

**Comment by zygoteplanets** [comment]
Any updates?

**Comment by sereneblue** [comment]
On the Live channel page where it shows the upcoming live streams, the dates are initialized with a value (from the data-timestamp attribute). Chameleon won't spoof these date objects because it breaks a lot of websites and libraries.

On the stream page, the initial value is sent from Youtube. For example, `Live in 2 days"},"subtitleText":{"simpleText":"April 22, 3:00 PM PDT"}`. This date is also initialized with a value.

If you want to spoof everything, feel free to use the [Spoof Timezone](https://addons.mozilla.org/en-US/firefox/addon/spoof-timezone/) extension.
