### ISSUE TITLE
Timezone is detected through javascript Internationalization API

### ISSUE THREAD

**Issue by loveerulz** [sereneblue/chameleon#167]
## Current Behavior
 i have set the timezone to -04:00 GMt in addon but in my system timezone is different (asia/kolkatta). In whoer.net website it show 100% anonymity but when i check at https://browserleaks.com/javascript it leaks the system timezone im attaching the screenshot please check... http://prntscr.com/nchgqd

**Comment by sereneblue** [comment]
This was mentioned in a previous issue, but I forgot to work on spoofing `Intl.DateTimeFormat`. I have this working now, however, it doesn't spoof everything, only the locale and timezone if they aren't specified.

**Comment by Thorin-Oakenpants** [comment]
> This was mentioned in a previous issue

@sereneblue Yeah, that was me :grinning: 

@loveerulz after sereneblue's patch, does anything still leak in https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#language

**Comment by sereneblue** [comment]
Just a heads up, you can run Chameleon from the repository source code by following the guide [here](https://github.com/sereneblue/chameleon/wiki/Debug). 

I can confirm the `Intl` API is spoofed, however, it can be a bit confusing because you're initializing the `Date` object with values so those values aren't spoofed.

**Comment by Thorin-Oakenpants** [comment]
> it can be a bit confusing because you're initializing the Date object with values so those values aren't spoofed

Is the test flawed?

**Comment by sereneblue** [comment]
No, it's not flawed. Currently, Chameleon doesn't spoof dates that have been initialized with a value but the `Intl` strings are spoofed so you'll get two conflicting values. Ideally, I'd like to have Chameleon spoof all the dates but messing with the `Date` object leads to breaking many sites. For ex, the Spoof Timezone extension breaks https://uk.megabus.com/ (mentioned in a previous issue).

**Comment by Thorin-Oakenpants** [comment]
Oh, well that's good then, because my task is to try and expose entropy (so we can fix it in Tor Browser and in FF's RFP) :)

**Comment by Thorin-Oakenpants** [comment]
PS: I'm not an evil genius or anything (maybe slightly evil, definitely no genius) - I only set a hard date/time so that comparisons would be cleaner. Now I'm quite chuffed it's exposed a shortcoming / made the test more robust.

Yup, going to build in ability to export/copy-to-clipboard and paste results into a compare page (quite some way off, so don't get too excited).
