### ISSUE TITLE
Some website are not dupe.

### ISSUE THREAD

**Issue by 945fc41467** [sereneblue/chameleon#19]
Hello,
If I go here : http://www.useragents.com/, the real user agent is displayed, even if script injection is enabled.

On panopticlick, the user agent is spoofed, but it still detect the real OS if script injection is disabled. This is not an issue by itself, but under the “enable script injection“ option, I can read “An option with * requires script injection“. And the “Profile” tab don’t display any “*”. You should indicate that this option require script injection until it can work without it.

**Comment by sereneblue** [comment]
I've identified the issue. It seems the document.write function call is being run before the extension gets a chance to modify anything.

I'll update the UI on the profile tab.

**Comment by sereneblue** [comment]
The execution of the document.write function call happens almost immediately after the async call that gets the injection script data. I've experimented with a small delay (would have been horrible hack) but it rarely worked. I've refactored some code to reduce the execution time for the async call but it's not enough.

The best solution I can come up with is to default all the variables being modified to an empty value before the injection script spoofs them. This generally shouldn't be an issue for normal websites since there's usually a few resources being loaded giving the extension enough time to build and execute the injection script.

**Comment by 945fc41467** [comment]
If I understand well, the website can have the real UA if it load fast enough.
I found another one : http://pgl.yoyo.org/http/browser-headers.php . Here, the OS is spoofed, but not the browser.
Thank for your work.

**Comment by sereneblue** [comment]
Where do you see the OS on that page? Chameleon doesn't have any issues with spoofing the header values that are returned.

**Comment by sereneblue** [comment]
I've changed it so that the default value is Chrome on Windows 10. An empty useragent could break some sites like Discord. Sadly, the user won't be able to change this because it goes back to the root issue. I just realized that I can read the settings in the content script but the code won't block.

**Comment by sereneblue** [comment]
@945fc41467 v0.6.7 should fix this issue.
