### ISSUE TITLE
keyboard fp protection renders input sluggish

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#199]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Expected Behavior
with the protection enabled input would not be impaired

## Current Behavior
with the protection enabled typing in various input fields renders the process sluggish. Example the search box (right hand upper corner) https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.16/administration-guide

disable the protection and reload the page to see the difference.

## Relevant settings
keyboard fp protection on/off

## Context (Environment)
N 69.0a1 (2019-06-08) on W10 Pro x_64 v1903

**Comment by sereneblue** [comment]
That indicates it's working. ;)

Keyboard fingerprint protection works by adding a delay between each keypress you make, making it much more difficult to identify you. I'll reduce the delay between each keypress in the next update; It should be a bit less noticeable.

**Comment by n8v8R** [comment]
any chance to add it to domain/ip whitelisting? 

Reason - places for online collaboration, e.g. Github or corporate intranet, having it enabled may lower one's typing rate whilst in general preferring the protection being enabled.

**Comment by sereneblue** [comment]
It's only enabled for inputs so it doesn't affect much larger bodies of text on the page (ex. comment boxes on Github) The new delay value (20ms instead of 30ms) makes it almost unnoticeable.

**Comment by Kraxys** [comment]
I think you should let the user to choose the delay, because on the other side the less the delay, the less the fp protection is working. There is a trade between protection and usability here.

The guy who first (to my knowledge) studied keyboard fingerprinting, P Moore, founded that with a default "dwell" and "gap" times to 200ms, keyboard fingerprinting failed in 99,98% of the case.  This value, 10 time higher than the value Chameleon currently uses, very probably leads to inconveniences, but the user should be able to select it if he want a very good protection against this fp method.. 

Ref:
https://paul.reviews/behavioral-profiling-the-password-you-cant-change/
https://addons.mozilla.org/en-US/firefox/addon/behavioral-keyboard-privacy/

**Comment by n8v8R** [comment]
I am turning the feature off altogether, even with 20 ms this feels like typing in molasses compared to my natural typing speed. I would not want to even near 200 ms, but that should be each user's prerogative .

**Comment by sereneblue** [comment]
I'll add an option for the user to configure this. I'm not entirely sure how effective this feature is though; see my comment [here](https://github.com/sereneblue/chameleon/issues/201#issuecomment-500625903)
