### ISSUE TITLE
Navigation Timing API

### ISSUE THREAD

**Issue by andcha88** [sereneblue/chameleon#243]
I've noticed that Chameleon won't spoof "Navigation Timing API" which actually reveals your real time and date of the device you use. @sereneblue could you please check this out? I don't know if it's possible to spoof these information but it would be great. Please find the attachment below showing the section which I'm referring to. I've already spoofed my timezone and all settings seems to be working fine but still showing my real time and date instead on this section.

Let me know if you need any further information or details to provide you. Thank you for the effort and work you do to make this for everybody to use :) You can find out on your own these information provided at https://browserleaks.com/javascript.

![Navigation Timing API](https://user-images.githubusercontent.com/55411029/65260502-213aba00-db0f-11e9-8bf8-4658645d270f.png)

**Comment by sereneblue** [comment]
Hi @andcha88,

Chameleon doesn't spoof the Navigation Timer API. I'll have to do some more research to learn how it works. Keep in mind that Chameleon's timezone spoofing is naive; it's still possible to get your real timezone. If you want to safely spoof your timezone, you should change your OS's settings.

**Comment by andcha88** [comment]
It would be a great option to be able to spoof Navigation Timer API. In the meantime, I'll make sure to change my OS's settings.

**Comment by sereneblue** [comment]
Hi @andcha88,

I've looked into this and it turns out it's not the Navigation Timing API that's displaying the time, it's using the regular Javascript Date API. Due to compatibility issues with third-party libraries that extend the Date object, Chameleon only spoofs the Date when it's initialized without any parameters. This is generally what's used for fingerprinting, however, this doesn't protect you from everything. I'd like to improve this further for [v0.20.0](https://github.com/sereneblue/chameleon/projects/1), but I'm not sure how much how I can improve the current functionality without breaking sites.
