### ISSUE TITLE
[Feature Request] Settings to automatically exclude old browsers

### ISSUE THREAD

**Issue by TheFrenchGhosty** [sereneblue/chameleon#257]
Some websites (including Github) display warnings about older browser that are no longer supported

Example:

![chameleon](https://user-images.githubusercontent.com/47571719/68340174-d3d5d480-00dd-11ea-8b26-c295239182b1.png)

It would be nice if there was an setting to automatically exclude them (similar to older version of Internet  Explorer).

**Comment by sereneblue** [comment]
Hi @TheFrenchGhosty,

You can manually exclude the older profiles from being used. Some more details about how profiles work can be found [here](https://github.com/sereneblue/chameleon/wiki/Profile). Also, you can whitelist a site so that it uses a specific profile.

**Comment by TheFrenchGhosty** [comment]
I know that I can do it manually, this is why this is a feature request, I'm requesting a way to have an automated way to do it.

**Comment by sereneblue** [comment]
There isn't a way to really automate this. Since there's only a handful of profiles, it's better to simply exclude the profiles you don't want to use. [v0.20.0](https://github.com/sereneblue/chameleon/projects/1) will improve on the browser profiles (more up to date) so you'll encounter these issues less often.
