### ISSUE TITLE
Can't add http://rarefilmnet.chatango.com/ to my whitelist

### ISSUE THREAD

**Issue by mondocane80** [sereneblue/chameleon#262]
- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Expected Behavior
Expect to whitelist _rarefilmnet.chatango.com_

## Current Behavior
Will not allow that syntax to be added to the whitelist.  I get a red line around the box and it will not save.  It will let me add _chatango.com_ to my whitelist, but that does nothing and still blocks the chat window over at _rarefilm.net_

## Relevant settings
Whitelist is ticked and enabled.

## Context (Environment)
Using Firefox 68.2.0 
Chameleon v0.12.19
Win7

After disabling Chameleon in Firefox, I can now view the chatbox again, so I know it's Chameleon that's blocking it. 

Since there's no toggle on/off feature on the Chameleon toolbar icon, I would have to constantly go in and enable/disable it all the time under Firefox's add-ons panel, which I'm not about to do.

**Comment by sereneblue** [comment]
Hi @mondocane80,

Thanks for opening an issue for this.

> Since there's no toggle on/off feature on the Chameleon toolbar icon,

I'm happy to say that this will be addressed when v0.20.0 is released. :)

Can you post your [settings](https://github.com/sereneblue/chameleon/wiki/About)? I'm not sure which setting is causing issues for you. I'm also curious why you're getting a validation issue when using `rarefilmnet.chatango.com`. I was able to create a whitelist rule like below: 
![image](https://user-images.githubusercontent.com/14242625/70101231-4f09a800-1602-11ea-8d5a-77d0b824ac83.png)

You may also want to whitelist `rarefilm.net`. Whitelist rules don't apply to iframes; this is something I haven't considered and may address in v0.20.0.

**Comment by mondocane80** [comment]
As you can see by the screenshot, the rectangular box is surrounded by a red border when I try to create.

![whitelist](https://user-images.githubusercontent.com/54923004/70189502-7b382e00-16c1-11ea-8db8-810d346d85cd.JPG)

**Comment by sereneblue** [comment]
> As you can see by the screenshot, the rectangular box is surrounded by a red border when I try to create.
> 
> ![whitelist](https://user-images.githubusercontent.com/54923004/70189502-7b382e00-16c1-11ea-8db8-810d346d85cd.JPG)
> 
> > You may also want to whitelist rarefilm.net. Whitelist rules don't apply to iframes; this is something I haven't considered and may address in v0.20.0.
> 
> Did that as well and it made no difference.

Hm, that's interesting.

Can you post your settings? It can be found on the about tab (tab with the question mark). It'll give me a better picture of where things are going wrong.

If your input matches any of the conditions below then the rule is not saved:

- Empty input
- It already exists
- A regular expression to validate the URL.

It seems the second condition is the cause of the whitelist rule issue unless there's a bug somewhere.

**Comment by mondocane80** [comment]
You're right, it was the second one.  I still had rarefilm.net in there.  I deleted that and was then able to add rarefilmnet.chatango.com

However, the frame for that chat window in that website still isn't showing.

Here's the ? tab

![setting](https://user-images.githubusercontent.com/54923004/70268445-79787400-176e-11ea-88c8-5817064610c5.JPG)

**Comment by sereneblue** [comment]
@mondocane80 Glad to hear that validation error wasn't a bug. This is another area of improvement for v0.20.0; helpful error messages.

Can you post the file that's created when you click the export button under settings?

**Comment by mondocane80** [comment]
Here's the file

[chameleon_1575671388864.zip](https://github.com/sereneblue/chameleon/files/3934283/chameleon_1575671388864.zip)

**Comment by sereneblue** [comment]
> Here's the file
> 
> [chameleon_1575671388864.zip](https://github.com/sereneblue/chameleon/files/3934283/chameleon_1575671388864.zip)

Thanks for posting your settings. Unfortunately, I'm still not able to replicate the issue. Loading rarefilm.net still shows the chat box. I'm not sure if Chameleon is conflicting with another extension or if's something else. Here are a few things you can try so that I can try to narrow down what's causing issues for you:

- Disable script injection. This is usually the cause of most issues with site breaking. If this works, that means one of the script injection settings is breaking the site.

- If the above doesn't work, try changing the following options:
  - Uncheck `Spoof source referer`
  - Set the Referer X Origin Policy to `Always Send`.

If the above doesn't work, can you upload a screenshot of your developer console by following these steps:

- Go to `rarefilm.net`
- Open the Developer Console by pressing Control + Shift + K.
- Click the console tab.
- Reload the page

It should look something similar to this:
![image](https://user-images.githubusercontent.com/14242625/70366503-d30f9a00-1865-11ea-9b12-7fbfc5e41c5d.png)

Please let me know the results.

**Comment by mondocane80** [comment]
Changing those three settings didn't do anything.  The frame is still hidden.

Here are my console settings

![console](https://user-images.githubusercontent.com/54923004/70398869-94a4e700-19ed-11ea-9c05-0402e2eaefaa.JPG)

**Comment by sereneblue** [comment]
@mondocane80 Did you change the cookie policy? 

I was not able to load the chat window using the `block 3rd party` or `block all` options. Unfortunately, blocking cookies can break sites so it's best to use the `reject trackers` option. Whitelisting wouldn't be of help here because the cookie policy is a browser level configuration. If you'd like more control over cookies, I recommend using [uMatrix](https://addons.mozilla.org/en-US/firefox/addon/umatrix/?src=search) for granular control or [Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers) for disposable tabs.

**Comment by mondocane80** [comment]
That actually worked.  Switching from "Allow Third Party From Visited" to "Reject Trackers" brought the frame back again.

I hope v0.20.0 will solve most of the issues brought up here.

Thanks!

**Comment by sereneblue** [comment]
@mondocane80 

Happy to hear you were able to get it working!

Thank you for submitting this issue; there's a few things its brought to my attention that will probably land in v0.20.0. I hope to have more details available soon to collect feedback from users after I have a beta version available.
