### ISSUE TITLE
[rfi] coexistence RFP and script injection

### ISSUE THREAD

**Issue by n8v8R** [sereneblue/chameleon#266]
Reading from this WX's wiki
>If you're using this feature, don't use script injection. More info can be found here.

brought me up short on what are the implications:

- if both, RFP and script injection are enabled, there would be apparent clashes, e.g.
  - spoofing time zone
  - spoofing audio context

and thus this RFI:

* which one takes precedence - RFP or the WX's script injection?
* does either inhibits the other in their functioniality, e.g. with RFP enabled the WX's script injection is not working at all or vice versa?
* could the both not coexist (complement each other), considering the aforementioned wiki statement?
___
Tests <sup>**[1]**</sup> indicate that:

- with both enabled RFP is not working
- disabling WX's script injection RFP is working but logically 
  - none of the WX's script injection options is applied
  - [navigator] userAgent is exhibited from RFP and not the WX
  - WX's header manipulation is still working
____
<sup>**[1]**</sup> https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html

**Comment by Kraxys** [comment]
> Tests **[1]** indicate that:
> 
>     * with both enabled RFP **is not working**
> 

> 
> **[1]** https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html

I don't agree with you on this  particular point. It seems rather than Chameleon takes precedence on RFP, but RFP is still working concerning the features not handled by Chameleon. For example, with RFP and script injection checked, with faking screen size to 1980x1080, and not faking timezone, I get on various tests sites 1980x1080 for screen size (chameleon takes precedence) , but for timezone I get GMT+00, which is RFP's time zone, so that RFP is still doing its job.

**Comment by sereneblue** [comment]
Hi @n8v8R,

I suggest that users not mix RFP and Chameleon's script injection features because they're fundamentally different. RFP (ideally) tries to make a user's fingerprint less unique similar to how the Tor Browser works. Chameleon allows you to have many fingerprints. RFP was provided as an option to make it more convenient for users to enable it with some of the other features. 

> Which one takes precedence - RFP or the WX's script injection?

Script injection works after RFP so it has final say in what values are being shown.
Depending on what Chameleon features are enabled, some RFP values may appear. As @Kraxys pointed out above, if a user enables RFP and doesn't spoof the timezone in Chameleon, UTC is used as the timezone (from RFP).

> does either inhibits the other in their functioniality, e.g. with RFP enabled the WX's script injection is not working at all or vice versa?

I don't believe there are any major conflicts. There may be some minor issues with the AudioContext and Client Rects features. Not sure yet, but I'll be revisiting these features soon for v0.20.0. RFP is known to break some sites and using that with Chameleon, also known to break sites, can lead to a less than stellar user experience when trying to figure out what's happening. 

> could the both not coexist (complement each other), considering the aforementioned wiki statement?

They can coexist. I suppose if you're using Chameleon with RFP, you'll have a flexible version of RFP; you get some of the benefits of spoofing/disabling some of the features listed [here](https://www.ghacks.net/2018/03/01/a-history-of-fingerprinting-protection-in-firefox/) and the variety of Chameleon's profiles/spoofing features. It really depends on what you want to use RFP for. If you want to use it as it was intended (similar to TBB mentioned above), it's best to not use Chameleon's script injection features.

> Tests **[1]** indicate that:
> 
>     * with both enabled RFP is not working
> 
>     * disabling WX's script injection RFP is working but logically
>       
>       * none of the WX's script injection options is applied
>       * [navigator] userAgent is exhibited from RFP and not the WX
>       * WX's header manipulation is still working
Hm, currently

**Comment by sereneblue** [comment]
Hi @n8v8R,

I suggest that users not mix RFP and Chameleon's script injection features because they're fundamentally different. RFP (ideally) tries to make a user's fingerprint less unique similar to how the Tor Browser works. Chameleon allows you to have many fingerprints. RFP was provided as an option to make it more convenient for users to enable it with some of the other features. 

> Which one takes precedence - RFP or the WX's script injection?

Script injection works after RFP so it has final say in what values are being shown.
Depending on what Chameleon features are enabled, some RFP values may appear. As @Kraxys pointed out above, if a user enables RFP and doesn't spoof the timezone in Chameleon, UTC is used as the timezone (from RFP).

> does either inhibits the other in their functioniality, e.g. with RFP enabled the WX's script injection is not working at all or vice versa?

I don't believe there are any major conflicts. There may be some minor issues with the AudioContext and Client Rects features. Not sure yet, but I'll be revisiting the code for features soon for v0.20.0. RFP is known to break some sites and using that with Chameleon, also known to break sites, can lead to a less than stellar user experience when trying to figure out what's happening. 

> could the both not coexist (complement each other), considering the aforementioned wiki statement?

They can coexist. I suppose if you're using Chameleon with RFP, you'll have a flexible version of RFP; you get some of the benefits of spoofing/disabling some of the features listed [here](https://www.ghacks.net/2018/03/01/a-history-of-fingerprinting-protection-in-firefox/) and the variety of Chameleon's profiles/spoofing features. It really depends on what you want to use RFP for. If you want to use it as it was intended (similar to TBB mentioned above), it's best to not use Chameleon's script injection features.

> Tests **[1]** indicate that:
> 
>     * with both enabled RFP is not working
> 
>     * disabling WX's script injection RFP is working but logically
>       
>       * none of the WX's script injection options is applied
>       * [navigator] userAgent is exhibited from RFP and not the WX
>       * WX's header manipulation is still working

Currently, script injection and header spoofing are almost two isolated features. The headers tab modifies the browser's web requests and script injection overwrites some client side JS objects properties. Only when the user enables script injection does the actual navigator properties get overwritten. 

I'm mulling over whether or not to remove the `Enable script injection` toggle in v0.20.0 because this doesn't seem optimal. If a user selects a profile, it _should_ automatically spoof the relevant browser properties. I believe most users probably use this feature to figure out if script injection is at fault for breaking a website. There will be an accessible button in v0.20.0 to toggle Chameleon from the popup so that should be a suitable alternative.

**Comment by n8v8R** [comment]
closing since the RFI been satisfied.

Just pointing out that `[navigator] hardwareConcurrency` however is not exhibiting a spoofed RFP value with the WX's script injection enabled.

**Comment by Thorin-Oakenpants** [comment]
> which one takes precedence - RFP or the WX's script injection

It depends on how RFP's implementation works, so you would have to test it: e.g:
- extension wins: RFP spoofs UA (HTTP header and navigator objects), but an extension can override those
- RFP wins: canvas returned as a 10x10 white square - extensions don't get to see the canvas request: but if you allow the canvas permission in site permissions, *then* the extension can see it and do what it wants

I expect the extension win in almost every case (canvas in my experience seems to be the odd man out).

I'm not recommending not to use both (RFP vs extension), because there are clearly use cases: e.g
- a UA spoofing extension can be used to overcome site compat
- you can allow RFP canvas so a site works, but then fake the canvas (and the site still works)
- a timezone spoofing extension could be used for e.g. gmail (you're already logged in) where it can be very frustrating with email timestamps across multiple devices/apps

My PoV is that in these situations, the default should be for the extension to do nothing, and the user should add domains to a whitelist

**Comment by Thorin-Oakenpants** [comment]
PS: also, toggling RFP on and off is not ideal. There are some cases (rare AFAIK) where changes don't take affect until the next restart

An example is Date/Time and timezone spoofing - see [1491343#c8](https://bugzilla.mozilla.org/show_bug.cgi?id=1491343#c8). Not sure if this is OS specific. This same issue (different cause) came up when they were plugging the locale leak in FTP (it was being debugged and worked on without e10s)
