### ISSUE TITLE
Block Scripts

### ISSUE THREAD

**Issue by Saadi1988** [sereneblue/chameleon#269]
using Spoof IP & Profile doesn't work on some websites. and WebRTC can't be blocked. and for example stats counter of [exampleblogservice].com shows our real info.
One of the deficiencis of this Chameleon is not having a script blocker. yea, i ican use extensions like NoScript & UMatrix. but they have not Ability to separate domain and subdomains. with "Whitelist" feature in Chameleon we can do this.
Thank you.

## Context (Environment)
Firefox Nightly 73 ; Windows 10 Pro

**Comment by sereneblue** [comment]
Hi @Saadi1988,

Blocking Javascript is outside the scope of Chameleon. uMatrix should get you pretty far because you can block/filter things at a subdomain level.

![image](https://user-images.githubusercontent.com/14242625/71560874-e3e9a080-2a0a-11ea-9cd3-5e2739753b4c.png)

The Spoof IP option of Chameleon **does not** spoof your real IP. It adds the `X-Forwarded-For` and `Via` HTTP headers to your requests with a spoofed IP address that can trick _some_ websites. WebRTC should be disabled If you enable the `Disable WebRTC` option. Did you test if WebRTC still works after disabling it?

**Comment by Saadi1988** [comment]
> 
> 
> Hi @Saadi1988,
> 
> Blocking Javascript is outside the scope of Chameleon. uMatrix should get you pretty far because you can block/filter things at a subdomain level.
> 
> ![image](https://user-images.githubusercontent.com/14242625/71560874-e3e9a080-2a0a-11ea-9cd3-5e2739753b4c.png)
> 
> The Spoof IP option of Chameleon **does not** spoof your real IP. It adds the `X-Forwarded-For` and `Via` HTTP headers to your requests with a spoofed IP address that can trick _some_ websites. WebRTC should be disabled If you enable the `Disable WebRTC` option. Did you test if WebRTC still works after disabling it?

yes, i have disabled WebRTC in Chameleon.

**Comment by Saadi1988** [comment]
uMatrix can't seperate main domain and subdomain. for example i want block scripts of "*.blogsky.com"  but i don't want uMatrix to block scripts in "blogsky.com/cpanel". because i need it.

**Comment by sereneblue** [comment]
If you want to hide your IP, I suggest you use a VPN service. 

https://fpn.firefox.com/
https://protonvpn.com/
https://thatoneprivacysite.net/#detailed-vpn-comparison

Disabling WebRTC doesn't hide your IP. It just prevents your real IP from leaking when using a VPN.

> uMatrix can't seperate main domain and subdomain. for example i want block scripts of "*.blogspot.com" but i don't want uMatrix to block scripts in "blogspot.com/cpanel". because i need it.

That's an interesting use case but unfortunately blocking scripts isn't going to be added to Chameleon.
