### ISSUE TITLE
Chameleon breaks fb lives

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#270]
# Prerequisites
- [x ] I am running the latest version
- x[ ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

## Expected Behavior
You can watch lives without issues

## Current Behavior
Pressing the button will just reload the video without playing it.

## Relevant settings
 https://privatebin.net/?218bff94e8695199#8wBxWLjQFBARvadw3yFH212ZbwgAnBuYmHGD5vVKxQat
## Context (Environment)
FF71 64 Linux, Lubuntu 18.04.

Note: chameleon breaks only lives live....you can watch them once they are finished without issues.

**Comment by sereneblue** [comment]
Hi @WPFilmmaker,

I don't have access to a Facebook live stream so I can't debug this issue, but I'm pretty sure it's related  related to script injection, most likely timezone spoofing. Can you post the errors in the output from the developer console during a live stream?

**Comment by WPFilmmaker** [comment]
I don't have access to such live now as well, Next time I have chance i will do as you said and post the errors;)

**Comment by sereneblue** [comment]
Hi @WPFilmmaker,

Thanks for looking into this. Unfortunately, that error message isn't too helpful. Can you try manually toggling the script injection features to see which one is causing issues? It may be best to whitelist FB live streams for now.

**Comment by WPFilmmaker** [comment]
@sereneblue I tried with 0.20 and the issue persist. I will check the script inection things once I have a bit of time ;)

**Comment by WPFilmmaker** [comment]
@sereneblue I tried with 0.20.8.1 and it is still broken. The new behavior is that the loading circle keeps loading forever. I tried disabling what I had enabled (etag protection, spoofing language, audio, client rects and font fingerprint(, once reloading I still had the same issue.

Whitelisting works, so does use 'real profile'. So it seems it is about the changed UA rather than ther settings (I am spoofing with WIndows 10 Chrome 81).

I would rather spoof on fb and live without lives rather than whitelisting fb (which I don't like anyway as it is so bloated). It just bugs me not to understand why they break. moreover it is a popular site so many users might encounter this issue, if I can provide more info in order to fix it would be great.

**Comment by sereneblue** [comment]
@WPFilmmaker This does seem to be caused by using a Chrome profile. I tried accessing https://www.facebook.com/watch/live/?ref=watch using a Chrome user agent on Firefox with Chameleon disabled and I get an error "Your Request Couldn't be Processed". Accessing one of the streams on that page also leads to an error.

It seems Facebook is using Chrome specific APIs or features. The whitelist can handle this depending on how you access live streams. 

For example, these URLs:
https://www.facebook.com/watch/live/?ref=watch
https://www.facebook.com/XYZ/videos/123456

can be matched to:

`www.facebook.com@@watch/live|videos/`

I'll be pushing out an update tomorrow to address an issue I discovered with the whitelist. Facebook uses `www.` and I'm sure many users normally wouldn't include this in the whitelist rule.

**Comment by GitGangGuy** [comment]
I don't want to be a jerk, but I'd recommend to stay away from Facebooks spyware hell as far as possible. I'd consider Chameleon breaking facebook lives as a feature! ;)

**Comment by WPFilmmaker** [comment]
@GitGangGuy you are indeed right, I try to avoid it as much as possible. FB is popular unfortunately, and if a user has to use it, I would say better with chameleon than without :)

**Comment by sereneblue** [comment]
@WPFilmmaker Were you able to resolve this issue by adding the whitelist rule I mentioned above?

**Comment by WPFilmmaker** [comment]
@sereneblue It works thank you!
