### ISSUE TITLE
Windows Mobile Phone Useragent request to add

### ISSUE THREAD

**Issue by koalarosa** [sereneblue/chameleon#276]
Hi

Can you add Windows Mobile Phone Useragent category like in Ras ?

In Chameleon I do not see any user agent of this category

This is the image of ras, these user agent can be used with Windows OS

[https://i.imgur.com/7CL6hUL.png](https://i.imgur.com/7CL6hUL.png)

Thanks

**Comment by sereneblue** [comment]
Hi @koalarosa,

I did not add Windows Phone or the other platforms to Chameleon because they're not as popular as they were while RAS was around. Chameleon's mobile spoofing will improve in v0.20.0; for each mobile profile, there's a variety of device fingerprints that could be used so it should offer some more diversity for mobile profiles.

**Comment by koalarosa** [comment]
Hi @sereneblue 

When will be publish chameleon v0.20.0 ?

Thanks for support

**Comment by sereneblue** [comment]
Hi @koalarosa,

There isn't a definite date yet but it should be released before the end of March. I'll try to get a beta out by next month for users to test. You can follow the status of progress of v0.20.0 [here](https://github.com/sereneblue/chameleon/projects/1).

**Comment by koalarosa** [comment]
Thanks
