### ISSUE TITLE
[REQ] Save data

### ISSUE THREAD

**Issue by Iquaridys** [sereneblue/chameleon#279]
can you add this in Headers,
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Save-Data

**Comment by sereneblue** [comment]
Hi @Iquaridys,

This header falls outside of the scope of what Chameleon offers. Is there any particular reason you want this header added? There are some extensions out there that can help you if you want to add this header to all requests.

**Comment by sereneblue** [comment]
Hi @Iquaridys,

This header falls outside of the scope of what Chameleon offers. Is there any particular reason you want this header added? There are some extensions out there that can help you if you want to add this header to all requests.

**Comment by Iquaridys** [comment]
in my country the internet is still developing I need to buy to an ISP around $10 for 10GB in 1 month, and this 3G network is sometimes 4G in my city, not fast compared to other countries.

Based on that and also to reduce the number of add-ons users I want Chameleon to be able to add it. And of course this is just a suggestion, considering I use chameleon too

**Comment by sereneblue** [comment]
I see. I won't add the header to Chameleon since it's a bit outside its scope but there's an existing extension that does what you're looking for: https://addons.mozilla.org/en-US/firefox/addon/save-data/. You may be able to save more data by using an IE11 (lighter pages for some sites) or mobile profile.
