### ISSUE TITLE
Video streaming fail and abort playback, "A network error caused the media download fail part-way"

### ISSUE THREAD

**Issue by johncock** [sereneblue/chameleon#28]
I experience problems streaming videos.
As soon as I click on the video to pause instead of pausing with the space bar, or trying to skip forward with the mouse instead of the arrow buttons on the keyboard the playback stops.
Movpod won't even play but displays a cross with an error message.
Many other sites have the same problem. These are just two examples I came across this morning when I had enough of this.

Error message is **"A network error caused the media download fail part-way"**.

I removed the extension and the problem is gone.
For now I reinstalled the old Random Agent Spoofer 0.9.5.6 to solve the issues I have.

See images below for reference:

### Openload
![openload](https://user-images.githubusercontent.com/23343303/42653536-02cde8f2-8616-11e8-9399-1a7b818dff45.PNG)
Backup link: https://cdn.pbrd.co/images/Hu9wiE3.png

### movpod
![movpod](https://user-images.githubusercontent.com/23343303/42653576-1a50f8de-8616-11e8-8865-4bfc2c5fe15c.PNG)
Backup link: https://cdn.pbrd.co/images/Hu9wfv3.png

**Comment by sereneblue** [comment]
I'm currently working on rewriting some of the setting code that I think might be causing issues. Have you enabled any settings? Can you post any error messages that you find in the developer console when trying to load a video?

**Comment by sereneblue** [comment]
I experienced issues trying to get a video to load on OpenLoad with Firefox and Chromium so I'm not sure if Chameleon is causing issues. I didn't have any problems getting movpod to play videos but it's probably because Chameleon was already configured for me.

I've cleaned up some code so the defaults shouldn't be messing with anything on the page. Can you try the latest version and let me know if that fixes anything for you?
