### ISSUE TITLE
user agents not generic

### ISSUE THREAD

**Issue by Dispositiv** [sereneblue/chameleon#29]
just saw your update on user agents. This are not real everyday values. Could you please integrate the list on https://techblog.willshouse.com/2012/01/03/most-common-user-agents/ (automatically updated there, why no 'update'-button cloning those values in the application?). btw: look at the percentage-rating there, this could also be a good hint for making your browser-user-agent-fingerprint even more generic.

**Comment by sereneblue** [comment]
I don't see the issue with the current user agents that Chameleon already offers? I didn't realize Chrome changes the user agent frequently between versions (I'll update them asap) but the user agents available are generally the most recent or common user agent for its respective browser and platform.

That website doesn't actually represent the most common user agents because the traffic has some bias (techies) although it's a good source to get up-to-date user agents.

You can exclude certain user agents to tailor Chameleon to your preference.
