### ISSUE TITLE
Load UA from txt file.

### ISSUE THREAD

**Issue by mazbron** [sereneblue/chameleon#303]
Hi,
I have feature request sir, 
Is possible to load custom UA from txt file?

Thanks

**Comment by sereneblue** [comment]
HI @mazbron, no, it's not possible. Just a heads up, custom user agents will be removed in v0.20.0. What is your use case and what custom user agents are using?

**Comment by mazbron** [comment]
@sereneblue Hi, I just use it for bot :D 
btw, will you release Chamelon for Chrome?

Thanks

**Comment by sereneblue** [comment]
@mazbron 

Unfortunately, I won't make a release for Chrome. 

If you're using the Chrome DevTools Network Protocol, there are some libraries like [Puppeteer](https://github.com/puppeteer/puppeteer) and [Playwright](https://github.com/microsoft/playwright) that you can use with Firefox. Selenium is another alternative. One of the good things about using Firefox for automation is that you can use addons in headless mode. With Chrome, you'd need to use xfvb.

The current version of Chameleon is a bit flexible because the logic is pretty clear for how spoofing works. Feel free to hack on it for your needs. Just a heads up, there are some major improvements in spoofing with v0.20.0 but it's a bit 'different' when it comes to screen size/profile spoofing. You may find [this]([url](https://github.com/sereneblue/chameleon/issues/301#issuecomment-600914870)) comment useful.

If you're using Puppeteer/Playwright, you may not actually need Chameleon for profile spoofing. You can implement most of Chameleon's logic in a script that is run when a new page is loaded using `page.evaluateOnNewDocument`. I'd use Playwright for profile consistency. There is a bug in Puppeteer where the script doesn't run in popups.

I'll be working on making Chameleon a little easier to interact with from scripts (adding attributes to inputs to make it easier for developers) and writing a guide to get started with using it in Selenium/Puppeteer/Playwright.

**Comment by mazbron** [comment]
@sereneblue 
Thanks for your reply.
May I can have your skype or email?
I have great method to make a tons of money, I already do this about 5 years.
We can works together if you want, sure we will make more money.

**Comment by sereneblue** [comment]
Hi @mazbron, I've created a contact form [here](https://sereneblue.github.io/chameleon/contact/) that you can use to get in touch.
