### ISSUE TITLE
Chameleon v0.20.0 does not remember UAs options selected in the previous version

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#323]
First of all thank you for the great extension, the new update rocks :)
I encountered an issue upon updating which I thought it was worth mentioning.

After updating I checked if the addon was working and noticed that the profile I was using as spoof was FF 68 desktop. I thought it was weird since I had excluded all variants except for Chrome on Windows. I checked in the settings and it seems that all linux and macOS profiles had been excluded, for Windows there are a few ones which were not excluded (including windows edge) which clearly overrode my settings from the previous version.

Am I mistaken or?

Thank you :)

Chameleon v0.20.0, FF 75.0 Linux, Lubuntu 18.04

**Comment by sereneblue** [comment]
Hi @WPFilmmaker, thanks for reporting this issue. The profile options didn't translate 1:1 so I had to make a few assumptions. Firefox ESR on Windows was only available for three OSs instead of 4 and Edge was only available for one in the legacy version of Chameleon, I forgot to take this into account. Not sure if you still have your old settings, but if you import them in the next update, it should only use the Chrome profiles.

**Comment by WPFilmmaker** [comment]
@sereneblue No prob, I was able to reinstall settings manually ;=)
