### ISSUE TITLE
0.20.0 update silently reset some about:config settings (e.g. disabled privacy.firstparty.isolate)

### ISSUE THREAD

**Issue by shvchk** [sereneblue/chameleon#334]
## Expected Behavior
Update should not silently change settings, **especially** privacy related. Users should be warned that some settings can not be changed in `about:config` anymore, only via Chameleon.

## Current Behavior
0.20.0 update disabled at least `privacy.firstparty.isolate` setting, I'm now checking for other `about:config` changes.

Just checked: it actually keeps disabling `privacy.firstparty.isolate` if you enable it in `about:config`, but not in Chameleon.

## Context (Environment)
Today I noticed I was logged out of sites I regularly use. Turns out `privacy.firstparty.isolate` was turned off, totally a WTF moment. The only thing that changed recently was Chameleon update (no other addons of Firefox updates, no settings changes recently).

Firefox 75, Ubuntu 19.10.

**Comment by sereneblue** [comment]
Hi @shvchk, sorry about that. I understand the magnitude of this issue. It was caused because of the initial settings migration after v0.20.0 loads. The settings that Chameleon used were ported over, but the Firefox preferences that Chameleon changes are not (the settings on the options menu under the standard and cookie tabs). They're treated a little differently. I've patched this bug but it may be too late. I only hope that Chameleon v0.20.0 was enough of a change that users were able to spot the changes in their settings.

**Comment by shvchk** [comment]
@sereneblue thank you for prompt response and fix, really appreciate it!
