### ISSUE TITLE
browser not support when login gmail/google

### ISSUE THREAD

**Issue by Iquaridys** [sereneblue/chameleon#339]
- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed

## Expected Behavior
Go SE , go to gmail , when input email, should go to password  but show browser not support
## Current Behavior
![image](https://user-images.githubusercontent.com/23011078/80895075-21d53900-8d0b-11ea-84a5-0391c15bf39a.png)
## Relevant settings
[chameleon_1588463586051.txt](https://github.com/sereneblue/chameleon/files/4569349/chameleon_1588463586051.txt)

## Context (Environment)
I try disabled chamelon work fine, when i try again turn on chameleon and reload browser no work again

Last Firefox
windows 10

**Comment by sereneblue** [comment]
HI @Iquaridys, do you have 2FA enabled for your account?

**Comment by Iquaridys** [comment]
no @sereneblue, i try again with tun off ' Protect window name ' work fine, when i turn on again the google login show browser no support

**Comment by sereneblue** [comment]
@Iquaridys, it's the browser profile being used that's causing issues. Some more details can be found in [this](https://old.reddit.com/r/qutebrowser/comments/cyb1wi/cant_sign_into_google/) reddit thread. The relevant part is from [this](https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html) link mentioned in the thread.

`Last year, we announced that we would require JavaScript to be enabled in your browser when you sign in so that we can run a risk assessment whenever credentials are entered on a sign-in page and block the sign-in if we suspect an attack. `

Google is doing some checks with JS to see if Chrome is actually being used. I'd normally leave this up to the user to whitelist `accounts.google.com` but since it's Google, it's probably best to disable spoofing on this page. I'll add a page to the wiki and something in the Chameleon UI so that users can easily find these "problematic" sites.

**Comment by WPFilmmaker** [comment]
I had the same issue before upgrading to the new version,
I disabled chameleon, logged in and renabled it:)

**Comment by sereneblue** [comment]
I've exempted accounts.google.com from being spoofed. This should be resolved in v0.20.3.

**Comment by WPFilmmaker** [comment]
@sereneblue is there a visibile list of domains which are exempted? I think it would make sense having such list (obviously as short as possible and togglabe off) because otherwise a new user does not know that spoofing is not possible on accounts.google.com.

**Comment by sereneblue** [comment]
@WPFilmmaker I've added a [page](https://sereneblue.github.io/chameleon/wiki/known-issues) to the wiki for this. It can also be found in the options page in v0.20.3.
