### ISSUE TITLE
Chameleon unchecks box, Delete cookies and site data when Firefox is closed

### ISSUE THREAD

**Issue by linksky56** [sereneblue/chameleon#346]
Hello,

Thank you for fixing issue #312 last week.

Found another glitch.

about:preferences#privacy
Cookie and Site Data
Delete cookies and site data when Firefox is closed

Whenever I enable Chameleon, it unchecks the box: Delete cookies and site data when Firefox is closed.
When you disable Chameleon, the check reappears. Enable Chameleon the check disappears again.

To use the *Delete cookies and site data when Firefox is closed* function (which I always use), I have to go to the * Manage  Your Extensions* page in Firefox and disable Chameleon, before I close the browser. Which also means that every-time I open the browser, I have to go to the extension page and re-enable Chameleon.

Hope you can help.
Thanks.

**Comment by sereneblue** [comment]
Hi @linksky56, 

Nice find! There are actually two cookie options that can be used, the cookie policy and whether to treat all cookies as a session cookie. Chameleon only configures the first one. It seems both should be set otherwise, it'll default the value to false. I'll add the second option to Chameleon which should resolve this issue. This should be available in the next update. Thanks!
