### ISSUE TITLE
Bug: About page icons not labeled after upgrade (so I inadvertently reset all my settings to default)

### ISSUE THREAD

**Issue by quietlystorming** [sereneblue/chameleon#348]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

I'm running FF 75.0, winx64 8.1

Issue:
So, I upgraded to v0.20.1, shiny new UI, and start looking around. I open the settings page and the About tab has all icons without text. I try clicking the ones on top - nothing happens. Of course, I then click the bottom-right icon wondering if it will exit me out. Again, nothing happens, or at least that's what I think. So I close the tab... only to come back later and realize that I reset all my settings to default. 

I haven't closed FF yet; is there any way to get my settings back? I saw a similar issue reported for the previous version that was closed as fixed, but here we are.

When I open the settings page now everything is actually labeled and working, btw.

**Comment by sereneblue** [comment]
Hi @quietlystorming, unfortunately, no, there isn't a way to get your settings back. Once the settings are reset, Chameleon reloads itself and the previous settings are removed. The issue you're referring to is slightly different. I'll add a confirmation modal in the next update to improve UX.

I'm not sure why Firefox has issues when displaying extension UIs. This is something I've seen in the past with a blank popup window with Chameleon v0.12.x and some other extensions. The reason why text isn't shown is because of localizations. The options page sends a request to the background script to get the text to display. It seems there was an issue there somewhere. I've added a cache to popup page to reduce the chances of this happening; it looks like I'll have to add it to this page too. Sorry for the inconvenience.

**Comment by quietlystorming** [comment]
sad_face, sad_face, sad_face. Well, hopefully this will help someone else going forward, thanks.
