### ISSUE TITLE
Chameleon Update breaks whitelisting feature

### ISSUE THREAD

**Issue by GitGangGuy** [sereneblue/chameleon#362]
This bug is the reason for issues #331, #342, #349 and #356, and I'm experiencing similar ones. I'd recommend to shift the discussion over to this, more general issue description.  
## Current Behavior
Since Chameleons new-UI releases (v2.0.x), the whitelisting feature appears to be broken. This is especially noticeable with pages like YouTube not loading properly anymore even though a whitelisting profile is set, as acknowledged by the add-on in the bar. None of the whitelisting settings however affect how chameleon processes the page. (Whitelisted! Real profile!) pages like apple.com claim I'd still be living in my spoofed timezone and location (from my spoofed ip-range). 

## Expected Behavior
This worked properly on pre-2.0.x releases, which is the reason why all these new issues are suddenly arising.
For now, I'll have to disable Chameleon. I really hope this can either be fixed by someone familiar with the code base in a PR or with a rollback to the previous version (with the better UI) until this gets fixed, as it brakes a lot of webpages I use daily.
**I understand that committing time, effort and money towards a free project isn't that rewarding, but there are a lot of people out there (like me) that love this extension and depend on it to confidently browse the web, without fear of fingerprinting and other shitty surveillance practices.**

## Relevant settings
Sample page: youtube.com
Whitelist profile: Real profile
Whitelist settings:
https://imgur.com/a/KFpboCy

## Context (Environment)
Latest Firefox version (76.0)
Latest chameleon version
Windows 10 (I heard this might be windows-specific)

**Comment by sereneblue** [comment]
Hi @GitGangGuy,

Thanks for being understanding. Most of the issues seem to have been caused by the fingerprint detection panel that was included in v0.20.0, but removed in v0.20.3. Some other issues were caused by the implementations of some of the injection features. There were some bugs that have been patched and there is still a performance issue that I'm working towards fixing sometime this week.

The header spoof IP feature does not spoof your actual IP address which is what apple.com seems to use to determine where you're from. It can trick _some_ sites.

Can you go to Youtube and verify that the whitelist profile is being used (open the Chameleon UI > whitelist tab > it should say youtube is whitelisted)?

If it is whitelisted, can you open the developer console and check to see if there are any errors being displayed?

Are there any other sites that you're experiencing issues with?

**Comment by WPFilmmaker** [comment]
@sereneblue don't want to hijack the ticket but does it mean that fingerprinting function was removed?or just changed? If you removed it do you plan to reimplement in the future?

**Comment by sereneblue** [comment]
@WPFilmmaker In v0.20.2-v0.20.2, there was a small UI panel at the bottom of the main popup panel. If a certain browser API was accessed on a page with Javascript such as the screen resolution, it would be shown in this panel. The problem with this feature is that the implementation causes a lot of issues. I don't plan to bring it back in the future.

**Comment by sereneblue** [comment]
@GitGangGuy Are you still experiencing issues with v0.20.8?

**Comment by GitGangGuy** [comment]
> Can you go to Youtube and verify that the whitelist profile is being used (open the Chameleon UI > whitelist tab > it should say youtube is whitelisted)?
As I described in my issue, Chameleon (as in versions before) reported that the visited page (like yt) was whitelisted, while it clearly was not. 
> If it is whitelisted, can you open the developer console and check to see if there are any errors being displayed?
Sorry, I can’t check right now. It still seems odd that it breaks all of a sudden.
> Are there any other sites that you're experiencing issues with?
All whitelisted pages, as described. They were using my real profile before, now they use the chameleon spoofed profile even though they’re whitelisted.

**Comment by GitGangGuy** [comment]
> @GitGangGuy Are you still experiencing issues with v0.20.8?

I’ll have to check, give me a few days

**Comment by GitGangGuy** [comment]
I'm not experiencing this issue anymore, so I'll be closing it.
I guess the update fixed it. Thanks a lot!
