### ISSUE TITLE
Still blocking something

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [sereneblue/chameleon#375]
With Chameleon enabled I can login to one of my banks and see the tab bar at the top of the page,  but the rest of the page is white - it won't display my account info. I can click the links in the tab dropdown menus and access different parts of the site, but I can't see any balances, transactions, payments due etc.

If I try to do a transfer I see this message:  **We are currently experiencing technical difficulties. Please try again later.** 

Disable Chameleon and I can complete the transfer.

Even after allowing ALL cookies in Chameleon, I can't view my account info or do transfers until Chameleon is disabled.

v0.20.8
FF 76.0.1

**Comment by GitTheHellOutaHere** [comment]
Just discovered I also can't log in to [this](https://www.fredmeyer.com/signin?redirectUrl=/cl/coupons/) site with Chameleon enabled.

**Comment by sereneblue** [comment]
Hi @GitTheHellOutaHere,

Can you post your settings?

**Comment by GitTheHellOutaHere** [comment]
Didn't figure it mattered since I tried changing most of them - unchecking Injection and Standard items, allowing all cookies, turning off Tracking protection mode and allowing all websockets. I usually set websockets to _block all_ since I really don't understand what they do or if they're necessary or if they are a privacy risk, even after reading descriptions of how they function.

I was about to say that I see we're now up to v0.20.9, but when I checked the release notes I saw that  v0.20.10 was released 7 hours ago; I manually installed it.

**Comment by sereneblue** [comment]
@GitTheHellOutaHere 

Every option except WebSockets found on the "Standard" and "Cookie" tabs are Firefox preferences that Chameleon can change. WebSocket is a new protocol that allows real-time communication between a server and a client. It's useful for sites that update data in real-time such as sport scores, chat messages, or multiplayer games. There are some potential security issues with them, notably [this](https://medium.com/@bjt2n3904/in-protest-of-the-web-bulldozer-e0fce4567d26).

A default Chameleon installation doesn't seem to break the site you linked to so its seems to be caused by an option that's enabled. The reason I ask for settings is because it's the best clue I have to reproduce the issue on my end. From a quick test of a few options, it seems blocking all cookies can break the site. Timezone spoofing can also cause some issues. For your banks' site, I don't know what the error is can't have offer much help unless I have some more information about the error. The [debug](https://sereneblue.github.io/chameleon/wiki/debug/) guide may be able to assist you to narrow the specific issue. Please note that whitelisting a site does not prevent it from being affected by the Firefox options mentioned above.

**Comment by GitTheHellOutaHere** [comment]
_AHA!_

Timezone was causing it. I didn't even think it was spoofed it because it was set to my actual zone and the setting no longer says **timezone spoofing**. But when I switched to Default, the site worked.

With it set to my zone I couldn't press the "sign in" button on [this](https://www.fredmeyer.com/signin?redirectUrl=/cl/coupons/) page - you can see there's a NO symbol on the cursor and the button is dark.

![FM login](https://user-images.githubusercontent.com/15519219/82744083-62046600-9d63-11ea-99dd-cafdff1b6bee.jpg)


I'll just keep timezone set to default and maybe that'll help with other sites as well.
Why does changing it to anything other than default cause problems, even if it's set to the correct zone?

**Comment by sereneblue** [comment]
@GitTheHellOutaHere 

Timezone spoofing is really an experimental feature. Chameleon overwrites how the normal `Date` object works. This breaks a lot of libraries that extend it. It's extremely difficult to get it "right" considering how it's implemented. I'm in the process of rewriting the implementation again. There's no reason to use timezone spoofing if you're going to use your actual timezone.

The default option for WebSockets is `Allow all`. Changing it to anything else will eventually cause an issue with a site, however, `Block 3rd party` is a good choice if you're comfortable with the developer console and debugging issues when a site breaks. Blocking all websockets will prevent many sites that use it from working (real time updates, notifications, etc).
