### ISSUE TITLE
Bring back youtube's old design

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#415]
Google decided to remove youtube's old design, which means if you are on FF the site will be slow. I had an addon to enable the old layout but it stopped working.

On reddit I found this solution:

"At least for me, when I set Firefox's user-agent to Google Bot (Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)), I get old design. I'm using User-Agent Switcher add-on. Good thing is that with this add-on, user-agent can be set per domain.

 
Here is more detailed help how to get back old youtube.com design
Firefox

Install User-Agent Switcher add-on. Click on the icon Enable Google Bot for youtube.com, as shown here.

 
Chrome (hat tip to /u/Tig3rj)

Install User-Agent Switcher for Chrome extension. After it is installed, right click on the mask icon at the top right and select options. Open Custom User-Agents from the left side menu and add new user-agent.

    New User-agent name: Googlebot
    New User-Agent String: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
    Group: Chrome
    Append?: Replace
    Indicator Flag: just put a 1 there

Next, in the left hand menu click on Permanent Spoof list.

    Domain:: youtube.com
    User-Agent String: select Googlebot"

The addon in question is: https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/

However I don't know how to replicate it in chameleon, could you please tell me/try and see if it works?

It is a temporary workaround I suppose...but better than nothing :)

**Comment by sereneblue** [comment]
@WPFilmmaker Chameleon doesn't have a way to use custom user agents but you can get this working with Chameleon by whitelisting `youtube.com`. Create a new rule for Youtube and selct "Real Profile" for the profile. Then, use User-Agent Switcher as mentioned above and you should get the older version of Youtube.

**Comment by WPFilmmaker** [comment]
@sereneblue Thanks for the explanation. I am sure there are reasons why you haven't implemented a custom user agent per site, would you consider this for the future? Or at the least would you share why you decided not to implement it?

**Comment by sereneblue** [comment]
@WPFilmmaker 

Pre-v0.20.0, there was an option to have a custom user agent. It would try to guess what navigator properties to use depending on the profile but this isn't foolproof.

Chameleon v0.20.0+ expands on profile spoofing with a dynamic profile generator. Each profile has a set of navigator properties and headers. This keeps things consistent and simple for maintenance. If I were to add the option to add a custom user agent, I'd have to open up adding other properties which isn't too simple (ex. fake plugins for Chrome profiles). I'm open to adding more profiles, but using a custom user agent is outside the scope of this extension.

**Comment by slrslr** [comment]
Hi, is Youtube working for You guys? For me it started displaying properly the comment section and sidebar videos after i whitelisted the site in chameleon... i am having v. 0.20.21, FF beta

**Comment by WPFilmmaker** [comment]
@slrslr does the above hack works for you? I haven't tried yet because I couldn't understand what to put in the string.

**Comment by slrslr** [comment]
I am not using Chrome but FF, if i recognize that hack correctly.

**Comment by WPFilmmaker** [comment]
The hack is for FF. I am on FF 78.0.1 and YT with the new design works fine it is just slow. Maybe try to post the settings here and a screenshot?

**Comment by slrslr** [comment]
I will not install any more addons. If needed, [here is my Chameleon configuration](https://defuse.ca/b/O492aGzdCyonn6SG5I3mQc). (pass word is cc)

**Comment by sereneblue** [comment]
@slrslr It depends on the profile. Youtube doesn't load properly if you're using IE11 as your profile. I'm not sure why but I can look into it.

**Comment by slrslr** [comment]
@sereneblue indeed, when Chameleon automatically changed the user agent profile youtube works. I click globe icon (Profiles) > Windows and i see i already have most IE11 profiles "excluded" from being used. Only one remained to be excluded so i cliccked to exclude this IE11 one. Maybe it will work now. I guess this setting is applicable for all domains, not just Youtube. So this is fixed. Btw. when chameleon is enabled there are stripes on the bottom of the videos (including full screen view): [image](https://i.postimg.cc/yVBBgS6b/youtube-stripes-video-bottom.jpg)

**Comment by sereneblue** [comment]
@slrslr If you disable Chameleon do those lines still appear? I can't replicate the issue. It seems more like it's driver related.

**Comment by slrslr** [comment]
@sereneblue I found the issue is tied to selected user agent profile: Win, Firefox ESR it was OK - no erroneous stripes. I changed profile in Chameleon, it picked Win 10, Chrome 83. Ctrl+F5, stripes appear. I randomized again, "Win 8.1 / Firefox 78 ESR" was picked, Ctrl+F5 and stripes away (OK). I change profile one more time, it pick "macOS 10.14 / Chrome 83" and stripes are back... I am on Firefox beta update channel, FF 79.0b7 (64 bit).. When browser was Safari, erroneous stripes was also there.. if you need some setting from firefox "about:support" page, i will supply it..

**Comment by sereneblue** [comment]
@slrslr I tested with FF 79.0b8 (64-bit) on Linux and I still wasn't able to replicate this issue. Does this happen on FF 78?

**Comment by WPFilmmaker** [comment]
@sereneblue is there any chance you can add google bot to the list of profiles shipped with chameleon? So one would just whitelist youtube and select google bot as profile?

**Comment by slrslr** [comment]
@sereneblue 
it was complicated to install FF v78, i did it and found that in blank new profile with chameleon enabled, chameleon config. imported, then the problem with [stripes](https://postimg.cc/7C2B2xXh) is not there. I also tried to launch FF v78 with other plugins and main config, but Firefox not allow me to use v79 config. If needed detail about my attempt to run old FF with new profile, its below:

I downloaded [FF 78](https://ftp.mozilla.org/pub/firefox/releases/78.0/win64/en-US/) and selected custom installation into custom directory. Launch it selecting new profile. Install same Chameleon version, load youtube and no problem with [stripes](https://postimg.cc/7C2B2xXh) on the video. Importing my Chameleon config and going to previously failed OS/UserAgent combination also no problem. Then restarting with my main profile from FF 79b. It then somehow silently opened v79b version of FF (as it was running already) instead of v78. I had to edit properties of Firefox desktop shortcut to be "C:\Program Files\Mozilla Firefox 78\firefox.exe" -P "mymainprofilename" -no-remote
But that warned me that the FF is runing, it closed my v79 and then warned me it may corrupt my profile to run older FF with my newer profile. I could duplicate my profile folder C:\Users\usernamehere\AppData\Roaming\Mozilla\Firefox\Profiles but FF does not allow me to use it warning about its corrupting.

**Comment by sereneblue** [comment]
@WPFilmmaker I won't add the googlebot profile. I'm not sure how long this workaround will continue to last. It seems even with the Googlebot useragent, [some parts of Youtube](https://old.reddit.com/r/youtube/comments/hoetae/youtube_is_trying_to_kill_off_prepolymer_for_the/) still render with Polymer. The IE11 profiles also used to render Youtube Classic but now the sites doesn't load with them.

@slrslr Sorry for the all troubles you went through. For future reference, I think you may be able to use [Firefox Portable](https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./) and not worry about your profiles getting mixed up. It seems Chameleon isn't the issue. Hopefully, the problem is resolved when FF79 is released for the stable channel. For best results with Youtube, I recommend whitelisting it with a Firefox profile.

**Comment by WPFilmmaker** [comment]
@sereneblue I understand,
I tried useragent but it didn't work for me, I suppose youtube managed to enforce its new design..closing this.
