### ISSUE TITLE
JIRA breaks with any "Screen size"

### ISSUE THREAD

**Issue by gcbw** [sereneblue/chameleon#449]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

## Expected Behavior

Expect to be able to scroll on JIRA(tm) issues: e.g. https://issues.apache.org/jira/browse/MCOMPILER-209

## Current Behavior

The scroll ends up shorter than the actual content.

This is clearly an issue with the site doing something silly. Maybe something else to add to "known issues"?

## Relevant settings

After much hunting, i'm able to reproduce based solely on `Options > Screen Size` being set to anything other than `Default`.

Depending on the size you select you get more scrolling region or less. Most cases will not be enough anyway. 

## Context (Environment)

tested on Firefox ESR68. Firefox 79. Firefox Aurora (nightly)

**Comment by gcbw** [comment]
Also, if you are logged on, some other elements will not work (or show up out of view? ...still wondering if I should bother to debug their proprietary code). E.g. the button labeled "workflow" with a dropdown arrow, will work fine and show a floating submenu when Chameleon is off, but will not show anything, nor throw error, of chameleon is on (could not nail down to a single option either)

**Comment by sereneblue** [comment]
Hi @gcbw,

It's probably the srollbar causing rendering issues. From my experience working with scrollbars, the available height is used to determine how the scrollbar is rendered. Chameleon modifies the available height so that's the source of rendering issues. There isn't a fix for this particular issue so it's probably best to whitelist Jira. 

I was able to replicate the second issue by enabling "Spoof font fingerprint". This should be resolved in the next update.
