### ISSUE TITLE
Spoof the use of adblock

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#46]
Currently iamunique.org is able to detect whether the user is using adblock or not, and chameleon can't protect against it. Since the use of adblockers despite being popular, is not that widespread overall, it would be good being able to mask its use. 

I have no idea (as the test doesn't tells that) how they do that and/if they use any specify adblocker for the test.

For reference the most popular adblockers (according to their websites' stats) are: 

Adblock Plus (+11m users) and Ublock Orign (+4.5m users) on Firefox 

and 

Adblock (+10m users) and Adblock Plus (+10m users) on Chrome.

**Comment by sereneblue** [comment]
Unfortunately, Chameleon won't be able to mask that. 

amiunique tries to load the script located here: `https://amiunique.org/assets/javascripts/advert.js`. Popular adblock extensions would block that script from being loaded because it's a script that contains `advert` in the name of the file. amiunique checks if that script has been run (did it create an element? set a variable?) and if it doesn't it knows the user is using an adblock extension. The problem is that each site might do something similar but different enough to prevent a generic anti-adblock extension from working reliably.
