### ISSUE TITLE
custom size screen

### ISSUE THREAD

**Issue by 3xploiton3** [sereneblue/chameleon#464]
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ yes ] I am running the latest version
- [ yes ] I checked the documentation and found no answer
- [ yes ] I checked to make sure that this issue has not already been filed

please add to make costum size screen, i want make my desktop browser like my mobile android
1080 x 2160

**Comment by Thorin-Oakenpants** [comment]
That would make you an outlier, if not outright unique. You cannot hide your OS from fingerprinters, so unless your desktop is Android, that's just stupid

Custom screen sizes should not be encouraged, because... people don't understand how entropy works: they shouldn't exactly be expected to know it all, and therefore it is the extension's job to protect them by not allowing counterproductive settings

**Comment by sereneblue** [comment]
Hi @3xploiton3,

If you use the `Profile` option for the screen size when using a mobile browser profile, your resolution should match specific devices (for example Pixel UA + screen resolution). On mobile, the real screen resolution is not used, so the [numbers](https://viewportsizer.com/devices/) are a bit different. As @Thorin-Oakenpants mentioned, custom screen resolutions are a bit counterproductive.
