### ISSUE TITLE
Uncommon platform string

### ISSUE THREAD

**Issue by Housies** [sereneblue/chameleon#501]
When I set Chameleon to one of the Windows profiles and visit amiunique.org, it reports my platform as "Windows NT 10.0; Win64; x64" with a similarity ratio of 0.03%, instead of the much more common "Win32". Is it worth changing this, or is there a reason for such a conspicuous string?

**Comment by Thorin-Oakenpants** [comment]
For Firefox, if you mean `navigator.platform`, it is meant to be `Win32` for legacy reasons, see [1472618](https://bugzilla.mozilla.org/show_bug.cgi?id=1472618)

![platform](https://user-images.githubusercontent.com/16656956/118151220-eaf82f80-b402-11eb-8c78-a6abc32864f5.png)

**Comment by Thorin-Oakenpants** [comment]
@sereneblue OT: are you spoofing hardwareConcurrency, because it never changes but is recorded in prototype lies

**Comment by Housies** [comment]
I think it is `navigator.platform`. I guessed `Win32` would be what Firefox shows by default. I'm wondering why Chameleon shows something else.

**Comment by sereneblue** [comment]
@Housies Thanks for catching that. It was a bug in Chrome profiles. I'll release an update today that should resolve this issue.

@Thorin-Oakenpants Yes, hardwareConcurrency is also spoofed.

**Comment by Thorin-Oakenpants** [comment]
> Yes, hardwareConcurrency is also spoofed

quote: "because it never changes"

**Comment by sereneblue** [comment]
> > Yes, hardwareConcurrency is also spoofed
> 
> quote: "because it never changes"

The value is overwritten so it's caught by the prototype lies. I've added some code to not overwrite a property if the spoofed value is the same as the original value.

**Comment by Thorin-Oakenpants** [comment]
It wasn't about the prototype lies being triggered and the random value matching the real value (or not being spoofed): a prototype lie just means, as a last resort (I prefer equivalency, mathematical proofs, leaks, methods, inference, game theory), the value can't be trusted. hardwareConcurrency is one such item

I don't know when you added hardwareConcurrency spoofing, I don't see a option for it in Chameleon's settings. A while ago I started recording "lies", "bypasses", and "methods" - it's a work-in-progress: lies are boxed in red, bypasses in a purple tinged grey. I frequently test chameleon and other extensions with everything turned on, to test as I go through this work-in-progress.

The hardwareConcurrency value is always colored up as a "lie" (i.e untrustworthy) but it is always my real value - in dozens, **_probably hundreds of tests and just as many browser sessions_**. I only noticed, some time ago, because it is now colored (not sure when I added the color on it)

So either it's not getting randomized when it should, or there is no option for it and it never happens, or something. Maybe I'm blind or doing something stupid, IDK

**Comment by sereneblue** [comment]
> It wasn't about the prototype lies being triggered and the random value matching the real value (or not being spoofed): a prototype lie just means, as a last resort (I prefer equivalency, mathematical proofs, leaks, methods, inference, game theory), the value can't be trusted. hardwareConcurrency is one such item
> 
> I don't know when you added hardwareConcurrency spoofing, I don't see a option for it in Chameleon's settings. A while ago I started recording "lies", "bypasses", and "methods" - it's a work-in-progress: lies are boxed in red, bypasses in a purple tinged grey. I frequently test chameleon and other extensions with everything turned on, to test as I go through this work-in-progress.
> 
> The hardwareConcurrency value is always colored up as a "lie" (i.e untrustworthy) but it is always my real value - in dozens, **_probably hundreds of tests and just as many browser sessions_**. I only noticed, some time ago, because it is now colored (not sure when I added the color on it)
> 
> So either it's not getting randomized when it should, or there is no option for it and it never happens, or something. Maybe I'm blind or doing something stupid, IDK

Oh, I see what you mean. Chameleon spoofs the value to 4 for desktop profiles (I'll add 2 as another option for some profiles). For mobile devices, it depends on the device but I believe they're all 8 now. There used to be other values for the older Android devices.

**Comment by Thorin-Oakenpants** [comment]
Ah, so that's why.. thanks :) It's not "randomized", it's returned as a static value (different for android). Is this controlled by the UA spoof used?

**Comment by sereneblue** [comment]
> Ah, so that's why.. thanks :) It's not "randomized", it's returned as a static value (different for android). Is this controlled by the UA spoof used?

Yes, it's determined by the profile used.
