### ISSUE TITLE
Screen Size Spoofing not working as expected

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#52]
FF ESR 60 64 bits on W7 - Chameleon 0.8.16

For modifying screen size spoofing, just letting script injection checked and selecting an other screen size doesn't work. In doing that the *true size of your screen* just leaks.

 In order modifying screen size works, one has to 1) *uncheck* script injection 2) select the new spoofed screen size ) *check* script injection again (verification and testing made on http://ip-check.info/  and https://browserleaks.com/javascript).

It would be far more convenient no to have to uncheck an then recheck script injection, and to just have to selecting new spoofed screen size.

**Comment by sereneblue** [comment]
Hm, that's odd. It shouldn't behave that way. I'm not encountering any issues. Are you referring to the browser _viewport_? If so, that's the expected behaviour. That's determined by the size of your browser window, zoom settings, etc. You shouldn't have to worry about it too much because it's usually not constant.

![image](https://user-images.githubusercontent.com/14242625/45580249-08912780-b85d-11e8-8469-a2af25100a35.png)
![image](https://user-images.githubusercontent.com/14242625/45580261-23fc3280-b85d-11e8-910e-b379f086d4e6.png)

**Comment by Kraxys** [comment]
It was really the screen size, and not the browser viewport or the size of the browser's window. 

But after several tests, I found the the reason: There was some interference between Chameleon and the FF addon  [*Audiocontext-Fingerprint-Defender*](https://addons.mozilla.org/en-US/firefox/addon/audioctx-fingerprint-defender) (whose purpose is to spoof Audio Context). 

On FF 52 ESR, I had *RAS* and *AFD* activated together without any screen size spoofing issue. But it seems the *Chameleon*'s screen size spoofing features doesn't work when *AFD* is active.  It sounds weird to me, because I don't see how screen size relates to audio. And especially it's really a pity because *AFD* is to my knowledge the sole FF addon able to spoof Audio Context.

**Comment by sereneblue** [comment]
I could add that feature to Chameleon. I'll have to look into it to see how it works.
