### ISSUE TITLE
Firefox ESR - about:config Different Settings?

### ISSUE THREAD

**Issue by 0pLuS0** [sereneblue/chameleon#528]
## Expected Behavior

To be able to pick true for security.ssl.disable_session_identifiers & plugins.click_to_play

## Current Behavior

In Firefox ESR 91.5.1 I only have; ```Boolean Number String``` 

## Relevant settings

Firefox ESR 91.5.1

```What do I do with both of these settings, since I don't have a False/True option?```

THANKS

Here are screen shots of both these settings in Firefox.

![plugins click](https://user-images.githubusercontent.com/36190223/157585322-5a256039-daca-485b-a128-aa3bb05e2be5.png)

![security ssl](https://user-images.githubusercontent.com/36190223/157585341-236d8be9-4df7-4c79-96c7-e75498971119.png)

**Comment by Thorin-Oakenpants** [comment]
`plugins.click_to_play` was deprecated in FF69, 2 years and 6 months ago - [1519434](https://bugzilla.mozilla.org/1519434) - what are you trying to achieve here, where did you get this snake oil

`security.ssl.disable_session_identifiers` is a hidden pref, i.e you need to create it. It is a boolean. Again, what are you trying to achieve here - there are fingerprinting and perf costs, and it's not effective unless you are also randomizing your IP (which you're not), and even then it's not the solution. The real solution is to use state partitioning, which is already enabled by default in FF95+ (it's called network partitioning)

Again, where are you getting this snake oil?

**Comment by 0pLuS0** [comment]
@sereneblue Hello... 

@Thorin-Oakenpants what snake oil are you talking about? Are you familiar with this project and use Chamelon? I'd assume someone replying would, and if you are, then I don't get your response at all.

Since all I was trying to do was change these options to what Chamelon is suggesting.

Chameleon's options suggest these;

```plugins.click_to_play >>true```

```security.ssl.disable_session_identifiers >> true```

**Comment by sereneblue** [comment]
:wave: Please be cordial with each other.

> `plugins.click_to_play` was deprecated in FF69, 2 years and 6 months ago - [1519434](https://bugzilla.mozilla.org/1519434) - what are you trying to achieve here, where did you get this snake oil
> 
> `security.ssl.disable_session_identifiers` is a hidden pref, i.e you need to create it. It is a boolean. Again, what are you trying to achieve here - there are fingerprinting and perf costs, and it's not effective unless you are also randomizing your IP (which you're not), and even then it's not the solution. The real solution is to use state partitioning, which is already enabled by default in FF95+ (it's called network partitioning)
> 
> Again, where are you getting this snake oil?

@Thorin-Oakenpants These Firefox preferences are from Chameleon's "checklist" of preferences that a user might want to enable. I haven't updated the list in ages so I'm sure there are some things that are out of date.

> @sereneblue Hello...
> 
> @Thorin-Oakenpants what snake oil are you talking about? Are you familiar with this project and use Chamelon? I'd assume someone replying would, and if you are, then I don't get your response at all.
> 
> Since all I was trying to do was change these options to what Chamelon is suggesting.
> 
> Chameleon's options suggest these;
> 
> `plugins.click_to_play >>true`
> 
> `security.ssl.disable_session_identifiers >> true`
> 
> So since there have been changes in Firefox, it made me assume these are prefered options to use, and since I can't, I was only asking what to do with these now is all, since there is no longer a true/false choice to pick.

@Thorin-Oakenpants is familiar with Chameleon and is also more familiar with Firefox about:config preferences than I am. I haven't kept the checklist up to date (barely any changes since I created Chameleon years ago).

`plugins.click_to_play` is no longer relevant.
`security.ssl.disable_session_identifiers` is a bit extreme for most people. I wouldn't recommend it if you're not familiar with what it entails. 

I'll probably remove this part of Chameleon and link to better maintained resources in the wiki.

**Comment by 0pLuS0** [comment]
Ok plugins.click_to_play is no longer relevant, and I'll just leave security.ssl.disable_session_identifiers alone.

Thanks

**Comment by 0pLuS0** [comment]
In FF ESR 91.5.1 security.ssl.disable_session_identifiers only has Boolean Number String

So if True was the choice to use for security.ssl.disable_session_identifiers, what would I do with it in FF ESR 91.5.1?

Thanks

**Comment by sereneblue** [comment]
@0pLuS0 True/False are boolean values.

**Comment by Thorin-Oakenpants** [comment]
> what snake oil are you talking about? Are you familiar with this project and use Chamelon? I'd assume someone replying would, and if you are, then I don't get your response at all.

The snake oil that these prefs either exist or do anything useful today. And the answers are "yes" and "yes" (in testing only). I was not aware there was a chameleon list of items, or had at least forgotten about it - since I only ever use the toolbar icon>panel to flip things when testing

I now see there is a plethora of items under a Checklist. Personally I think that needs a cleanup or should be removed as feature creep and an unnecessary maintenance burden

for example: `browser.display.use_document_fonts` is not only obsolete but breaks sites - instead you can set a font vis pref. The SB prefs are excessive (you don't need all of them). Considering users, such as OP, are just blindly happy to apply these, I find recommending disabling SB as a bit irresponsible, esp when the only privacy concerns are real-time binary checks. TP's social list is redundant. Disabling PDFJS is also terrible (PS: RFP is going to enforce that as true for this very reason: to prevent separation of app state)

Not going to go thru all of these, but IMO this checklist should be removed - leave it to others who maintain and know this stuff. Up to you blue

**Comment by Thorin-Oakenpants** [comment]
> I'll probably remove this part of Chameleon and link to better maintained resources in the wiki.

Good. Still leaves you maintaining the wiki (which I haven't looked at). You could always just point at arkenfox - I'm sorry it recommends against any anti-FPing extensions in favor of RFP, and then only recommends kkapsner's as an alt (because it has canvas = in 99.99%  of naive scripts). So up to you
