### ISSUE TITLE
Question: Where's The Check List For about:config Options?

### ISSUE THREAD

**Issue by 0pLuS0** [sereneblue/chameleon#552]
# Prerequisites

- [ x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

## Expected Behavior

Should see the Check List in the settings.

## Current Behavior

I don't see any Check List in the settings

## Context (Environment)

FF ESR 102.4.0 - Linux
FF ESR 102.5.0 - Windows

I'm using chameleon 0.22.36

In past versions of chameleon it had the Check List option, that showed settings for about:config, I don't see these now, what happened to them?

Here's a screen shot of all I see now, without the Check List at the top.

![Settings](https://user-images.githubusercontent.com/36190223/202931512-c4b80794-b3a4-4f0c-a778-18b0d661b325.jpg)

THANKS

**Comment by sereneblue** [comment]
Hi @0pLuS0, this was removed in a previous Chameleon version because it was not maintained. A new resource was added to the [wiki](https://sereneblue.github.io/chameleon/wiki/resources), Arkenfox's user.js repository, which is essentially a better, maintained version of what the checklist provided.

**Comment by 0pLuS0** [comment]
Hi @sereneblue you're the DEV, so what do you mean not maintained, because you don't feel like doing this? Now this is a half baked solution, before, it was more complete. I honestly don't want to run around looking for JS files to incorporate and reading other wikis and hasslening with this and I'm sure a lot others are going to feel this way.

You don't need to have 75 options changed in FF to offer good solutions here for Privacy/Fingerprint, etc... anywhere from only 12-20 things is all that's needed, it's not a lot and it's certainly not all that complex, so I'm not sure why you think it is.

A lot of what people do out there is just over kill. Adding in No Script as an example and not allowing Java Script, takes care of a lot of problems.

So I'm really at a loss as to why you don't keep in the Check List. 

This is really sad, please put back the Check List, and put in whatever you can handle.

THANKS

**Comment by sereneblue** [comment]
> Hi @sereneblue you're the DEV, so what do you mean not maintained, because you don't feel like doing this? Now this is a half baked solution, before, it was more complete. I honestly don't want to run around looking for JS files to incorporate and reading other wikis and hasslening with this and I'm sure a lot others are going to feel this way.
> 
> You don't need to have 75 options changed in FF to offer good solutions here for Privacy/Fingerprint, etc... anywhere from only 12-20 things is all that's needed, it's not a lot and it's certainly not all that complex, so I'm not sure why you think it is.
> 
> A lot of what people do out there is just over kill. Adding in No Script as an example and not allowing Java Script, takes care of a lot of problems.
> 
> So I'm really at a loss as to why you don't keep in the Check List.
> 
> This is really sad, please put back the Check List, and put in whatever you can handle.
> 
> THANKS

The checklist was barely updated since Chameleon was created. Many settings are no longer relevant. It's not that I don't feel like maintaining it, it's more that I haven't. I don't have the time to keep up with all of the changes. The preferences found [here](https://github.com/arkenfox/user.js/blob/master/user.js) are more extensive and thoroughly documented than what Chameleon offered. If you have any questions, there's also a community of users available who would more likely than not better be able to answer any questions about a specific preference.

I'd rather point the community to something that's actively maintained than keep a neglected handful of checklist options.

**Comment by 0pLuS0** [comment]
We all understand Life takes priority, and I didn't mean to make this sound rude, it's just sad.

It just felt like a more complete soultion before, not it doesn't, and needing to run around looking for about:config options, isn't fun.

Have to had a chat with arkenfox, to see if you can do something here to implement this in some way into chameleon? Maybe not all of the options, but something partial, to make chameleon more complete.

THANKS

**Comment by sereneblue** [comment]
> We all understand Life takes priority, and I didn't mean to make this sound rude, it's just sad.
> 
> It just felt like a more complete soultion before, now it doesn't, and needing to run around looking for about:config options, isn't fun.
> 
> Have you had a chat with arkenfox, to see if you can do something here to implement this in some way into chameleon? Maybe not all of the options, but something partial, to make chameleon more complete.
> 
> THANKS
> 
> P.S. I see there's a GUI showing options, which makes it easier to follow, instead of looking through a .js file.
> 
> https://arkenfox.github.io/gui/

Thanks for finding that link. I've update the wiki to point to that instead of the repository. No, I haven't spoken with arkenfox to add these settings to Chameleon. I think the link you provided is ideal, it has filters and provides context for the about:config options.

I don't see the need to include this in Chameleon since it'd be the same content. Any user that's comfortable with modifying about:config should be able to find an alternative to the checklist or will explore the wiki and eventually find arkenfox's guide.
