### ISSUE TITLE
Chameleon vs Chameleon legacy[question]

### ISSUE THREAD

**Issue by kryptobolt200528** [sereneblue/chameleon#574]
Hello there, thanks for maintaining this wonderful extension,while i know that issues is meant for bugs,i couldn't help myself as an aspiring dev to ask this question.

What change in firefox v75(privacy api)prevents chameleon from modifying the privacy settings (listed under option>standard and cookies)?

**Comment by sereneblue** [comment]
Hi @kryptobolt200528,

Chameleon used to assume control of privacy related preferences like resist fingerprinting or the cookie policy upon install. This was changed so that the user would need to explicitly grant this permission to Chameleon. In Firefox pre-75, it was not possible for the privacy permission to be optional. The legacy version of Chameleon was made for Firefox users on Android who still used Firefox 68 (before Fenix).

Note, with the recent announcement of support for extensions on Android, the legacy Chameleon version is now deprecated and will eventually be retired.

**Comment by kryptobolt200528** [comment]
> Hi @kryptobolt200528,
> 
> Chameleon used to assume control of privacy related preferences like resist fingerprinting or the cookie policy upon install. This was changed so that the user would need to explicitly grant this permission to Chameleon. In Firefox pre-75, it was not possible for the privacy permission to be optional. The legacy version of Chameleon was made for Firefox users on Android who still used Firefox 68 (before Fenix).
> 
> Note, with the recent announcement of support for extensions on Android, the legacy Chameleon version is now deprecated and will eventually be retired.

Thanks for your quick response and concise explanation 😃.
