### ISSUE TITLE
ClientRects break some website

### ISSUE THREAD

**Issue by xesofes** [sereneblue/chameleon#61]
Hi,

Since the Client Rects update I can't load some website properly, for example https://startpage.com/ only work (when doing a research) with client rects unchecked. Can you look into this ? 

Thanks

**Comment by sereneblue** [comment]
I'm not experiencing any issues with StartPage. It may be a conflict with another extension or your configuration. Can you post your Chameleon settings and any errors that appear when you open the DevTools console tab on StartPage?

**Comment by Kraxys** [comment]
@xesofes: Have you Canvas Blocker activated at the same time? Since the last update 2 days ago, CB handles ClientRects (it blocks ClientRect, while Chameleon fakes it). These two options are not compatible, and when activated together, I get problems on StartPage too (no search results displayed). No more problems when I deactivated one of these options. The one you have to deactivate depending whether you prefer to block or to spoof.
