### ISSUE TITLE
Client Rects Spoofing detected

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#66]
On [Kkapsner Test Site](https://kkapsner.github.io/CanvasBlocker/test/detectionTest.html) ClientRect Spoofing is detected by 2 tests **(property descriptor** and **known DOMRect**).

**Comment by sereneblue** [comment]
Thanks for bringing this to my attention. I've fixed the property descriptor, but for known DOMRect, there's nothing I can do about that.

When Spoof Client Rects is disabled:
Expected Client Rect: 1.25
Actual Client Rect: 1.25

When Spoof Client Rects is enabled:
Expected Client Rect: 1.25
Actual Client Rect (spoofed): 1.25 + a tiny value to give you a unique client rect on every page you load.

That's the goal of spoofing client rects. If someone's using other addons to blocks ads and whitelist javascript, there's not much to worry about.

**Comment by ajruckman** [comment]
@sereneblue can you push 0.9.1 to the Firefox Add-ons site?

**Comment by sereneblue** [comment]
Yes, I'll do that now.

**Comment by Anderhar** [comment]
> Yes, I'll do that now.

I would like to revive this issue by reporting that Chameleon is detectable again by the specific pattern it uses to alter DOMRect. This unpleasant discovery I made thanks to this project: https://github.com/abrahamjuliot/creepjs

**Comment by Thorin-Oakenpants** [comment]
> thanks to this project

thanks to TZP (creepy got them from me: we work together a lot): three methods
- random per execution (by running two passes) - i don't think anyone spoof this way for domrect
- comparing the differences between two tests: one in the original position, the other shifted by css [1]
  - so if we moved it `0.25` then the diffs should be 0.25
  - chameleon changed (or used to change) each value by the same random tiny amount, rather than randomize each one individually, so it passed this test
- using a knownValue test (because methods like chameleon's weren't detected by shift)
   - I devised one that is zoom resistant (on Firefox, in chromium it has some diffs - IDCare about non-gecko TBH)
   - here's my really lazy PoC (but it is in TZP, and creepster uses this as well AFAIK)
   - https://arkenfox.github.io/TZP/tests/domrectspoof.html
   - I should get around to updating it - add a resize event, add all the call methods, but in the meantime you can just zoom & refresh
- here we can actually fingerprint the spoofing method: e.g. persistent diff (Chameleon) or random diff (CanvasBlocker)
   - it's on my list to update to TZP

I'll say it once, I'll say it again - if you lie, I can detect it: canvas, audio, textmetrics, ua, screen, domrect .... I just haven't added them all top TZP - but ... that's OK .. detecting the lie is one thing, just as long as you protect the real value (limited APIs - e.g. in service workers): and randomizing will help make scripts naive, and naive scripts probably aren't too sophisticated to go digging into service workers etc

[1]
```css
.divrect1 {
  top: 0;
  left: 0;
}
.divrect2 {
  top: 0.25px;
  left: 0.25px;
}
```

**Comment by sereneblue** [comment]
Thanks @Thorin-Oakenpants. @Anderhar As mentioned above, it's not too much of a concern.
