### ISSUE TITLE
2 Most Common Smartphone's Screen Size Are Missing

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#73]
In 2017 and 2018 the [most](https://rankuphub.com/most-popular-smartphone-screen-sizes-2018/) [common](https://deviceatlas.com/blog/most-used-smartphone-screen-resolutions) screen sizes for smarphones are **720x1280**, **750x1334** and **1080x1920**.

Currently, only 1080x1920 belongs to the Chameleon's screen size spoofing list.

I think these 3 sizes should **by default** belong to the screen size spoofing list, and should be used when the spoofed UA is a smartphone UA (when profile is set to "_Random_" or "_Random Mobile_",  script injection checked and Screen Size Spoofing set to "_Profile_").

**Comment by sereneblue** [comment]
Using a mobile device is a little different. 

https://mediag.com/news/popular-screen-resolutions-designing-for-all/

You don't get the actual screen resolution, only the viewport. If you visit https://browserleaks.com/javascript on a mobile device, you should see the browser viewport size instead of your device's actual resolution.
