### ISSUE TITLE
No more etag spoofing ?

### ISSUE THREAD

**Issue by Stratapo** [sereneblue/chameleon#89]
Hi,

I've seen in the commit that you removed the etag feature, Why ?

Thanks

**Comment by alekksander** [comment]
+1
(it's what made me interested in this project in first place)

**Comment by Kraxys** [comment]
It's a bit strange, but maybe this feature caused some breakage elsewhere??

Anyway, I never used this Chameleon's feature because I ceased to use its R.A.S counterpart when I realized that the testing site ip-check.info found something unusual when activated. On FF Quantum I use the addon [Etag Stoppa](https://addons.mozilla.org/en-US/firefox/addon/etag-stoppa/), which works really well (On tests I just performed on test site [cookielesscookies](https://lucb1e.com/rp/cookielesscookies/), Etag Stoppa does a better job in preventing Etag tracking than Chameleon 0.9.9 with "Spoof if-None-Match enabled).

An other (quite radical) way for getting rid of etag tracking is to completely disable the cache (disk + memory).

Or, you can use [Header Editor](https://addons.mozilla.org/en-US/firefox/addon/header-editor/) as explained by the Ghack Userjs team [here](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.4-Header-Editor) (not tested).

**Comment by sereneblue** [comment]
As I was writing tests for Chameleon, I realized that the "If-None-Match" feature doesn't work in Chameleon. I stumbled upon the documentation for the requests headers on [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeSendHeaders); tldr WebExtensions can't modify some headers and If-None-Match is one of them. I removed the feature because it didn't work and I (incorrectly) assumed that there was nothing I could do to fix it.

Fortunately, after doing some more research, I found out that there is a [way](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.4-Header-Editor) to fix this issue! Instead of modifying the request headers, I could modify the response. 

Etag spoofing will be back in the next update. Sorry for the confusion.

**Comment by Kraxys** [comment]
> 
> 
> As I was writing tests for Chameleon, I realized that the "If-None-Match" feature doesn't work in Chameleon. 


> Fortunately, after doing some more research, I found out that there is a [way](https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.2.4-Header-Editor) to fix this issue! Instead of modifying the request headers, I could modify the response.
> 
> Etag spoofing will be back in the next update. Sorry for the confusion.


This explains why the Chameleon's anti Etag tracking feature performed so bad when I tested it some hours ago before replying to Alekksander and Stratapo, and why ip-check.info detected nothing unusual. In fact, the functionality  didn't work at all :) 

Thanks for reintroducing this feature in the next version. This time enabling it will surely be able to entirely replace Etag Stoppa. Thanks for your work.

**Comment by Rafa2F** [comment]
Thank you very much for the work of developing this system. One suggestion: it would be nice if you spoof language for the ip, just like you need to update this one missing many time zones and languages. If you want I can provide a list http://www.lingoes.net/en/translator/langcode.htm

**Comment by sereneblue** [comment]
Good idea. `https://ipapi.co/json` provides the accept-language headers depending on your IP. It's already being used for the timezone feature, should be straightforward to implement.

**Comment by Kraxys** [comment]
This would be an other cool feature. But it has to be entirely optional. Else, eg non Chinese/Russian speaking users will have to struggle against Chinese/Russian displayed pages just because they use a proxy in China/Russia.

In the same vein: Why not fake the geolocation (the one related to the geo.wifi.uri preference) according to the IP? The addon [Location Guard](https://addons.mozilla.org/en-US/firefox/addon/location-guard/) does a good job in that matter (at least concerning the fixed location spoofing mode), and all that is missing is the adjustment of this location according to the IP....

**Comment by sereneblue** [comment]
Yes, it would be optional, similar to how the timezone option works now. If I recall correctly, the user has to explicitly grant a website permission to use the geolocation feature. I'm not sure it's worth adding.

**Comment by sereneblue** [comment]
@Rafa2F  @Kraxys I have added the option to spoof the accept-language by IP in v0.9.18.

**Comment by Rafa2F** [comment]
Great job, I'm using it and this feature helped a lot, thank you very much. I have another issue also would be very useful if I could add more than one user agent and create categories of user agents and there are still many time zones mainly from Australia.

**Comment by sereneblue** [comment]
For future reference, please create a new issue if you'd like to post something that's unrelated to a closed one.

I won't be adding a way to add more than one user agent. If you want to make the necessary changes, you should fork Chameleon.

I'll add the missing timezones in the next update. :)
