### ISSUE TITLE
Random Startup and More Choice

### ISSUE THREAD

**Issue by zygoteplanets** [sereneblue/chameleon#96]
Would it be possible to have an option to choose a new browser spoof, timezone and resolution automatically each time the browser is started up? With each random for browser spoof, timezone etc being separate eg. resolution only is randomized at startup if desired.

Also would it be possible to have more options when it came to browser configurations to choose from?

**Comment by sereneblue** [comment]
If you select one of the 'random' profile options, it'll randomly use a profile when the browser starts up. If you use 'Profile' for the screen resolution, it'll automatically change when the profile changes. 

I don't see a reason to use a random timezone because that would be counterproductive, however, if you're switching IPs in between browser restarts, select the 'IP' option for timezone and it'll also change the timezone randomly. The only issue with this one is that the timezone may be set to UTC if the IP is low quality (Cloudflare).

I won't add  more options for browser configurations because there's already enough. I'm not sure what you're trying to do (possibly automation related?), but feel free to fork Chameleon. You can add more profiles to `src/js/data.js`. As long as you're using modern browsers for the user agents, it should automatically spoof everything.
